### ISSUE TITLE
Does this library use Authorization Code or Implicit Flow?

### ISSUE THREAD

**Issue by umekun123** [nxtbgthng/OAuth2Client#145]
Sorry, this could be a stupid question.
I read it uses http://tools.ietf.org/html/draft-ietf-oauth-v2-10#section-1.4.3, but I'm still not sure if that means this awesome library uses Implicit Flow or not.

Also, if this library doesn't use Implicit Flow, why?

**Comment by toto** [comment]
Nope, we support all but implicit flow. We support: 
- Resource Owner Password Credentials
- Authorization Code (the default)
- [Assertion Flow](http://tools.ietf.org/html/draft-ietf-oauth-v2-10#section-4.1.3)

**Comment by umekun123** [comment]
Thanks for your quick answer, so Implicit Flow is not good for iOS apps?  If so, why?

**Comment by toto** [comment]
That depends. With Implicit Flow you cannot validate the identity of the client app (because no secret is used). This has the advantage that nobody can steal the secret, but you do not gain much because with the app ID everybody can impersonate the client. Therefore using a secret is preferable. 

The RFC talks about the downsides of implicit flow in great detail. That does not stop some very large users of OAuth (Facebook) from only relying on implicit flow. This basically means that you can impersonate any FB Connect app with not much effort. If you use implicit flow you should ensure to use [certificate pinning](https://github.com/nxtbgthng/OAuth2Client/wiki/SSL-TLS-Certificate-Pinning).

**Comment by toto** [comment]
That said, we could add support for implicit flow and given the time or a contributor we probably should. The lib needs to be updated for the RFC specs anyway, so this would be a good opportunity to add it. Given the current implementation it should not be complicated to add. If you want to give it a try look at the NXOAuthClient class as this does all the heavy lifting.

**Comment by umekun123** [comment]
Thank you very much for educating me a lot, I really appreciate it.
